INSERT INTO users (username, password, role) VALUES ('admin', '{noop}admin123', 'ROLE_ADMIN');
INSERT INTO sellers (name, email, phone, gst_number) VALUES ('ABC Distributors', 'abc@example.com', '9876543210', '22AAAAA0000A1Z5');
INSERT INTO products (name, category, price, description) VALUES ('Tata Salt', 'FMCG', 2028.51, 'High quality Tata Salt');
INSERT INTO products (name, category, price, description) VALUES ('Aashirvaad Atta', 'Pharma', 2874.91, 'High quality Aashirvaad Atta');
INSERT INTO products (name, category, price, description) VALUES ('Amul Butter', 'Textiles', 1456.59, 'High quality Amul Butter');
INSERT INTO products (name, category, price, description) VALUES ('Maggi Noodles', 'Pharma', 4997.81, 'High quality Maggi Noodles');
INSERT INTO products (name, category, price, description) VALUES ('Britannia Good Day', 'Textiles', 4164.58, 'High quality Britannia Good Day');
INSERT INTO products (name, category, price, description) VALUES ('Parle-G', 'Textiles', 4829.27, 'High quality Parle-G');
INSERT INTO products (name, category, price, description) VALUES ('Haldiram Bhujia', 'Textiles', 776.5, 'High quality Haldiram Bhujia');
INSERT INTO products (name, category, price, description) VALUES ('Surf Excel', 'Electronics', 4942.21, 'High quality Surf Excel');
INSERT INTO products (name, category, price, description) VALUES ('Rin Soap', 'FMCG', 1429.98, 'High quality Rin Soap');
INSERT INTO products (name, category, price, description) VALUES ('Lifebuoy Soap', 'Groceries', 2808.74, 'High quality Lifebuoy Soap');
INSERT INTO products (name, category, price, description) VALUES ('Dettol Liquid', 'Groceries', 761.18, 'High quality Dettol Liquid');
INSERT INTO products (name, category, price, description) VALUES ('Colgate Paste', 'Textiles', 4088.31, 'High quality Colgate Paste');
INSERT INTO products (name, category, price, description) VALUES ('Pepsodent Paste', 'Electronics', 4847.64, 'High quality Pepsodent Paste');
INSERT INTO products (name, category, price, description) VALUES ('Fair & Lovely', 'Electronics', 735.87, 'High quality Fair & Lovely');
INSERT INTO products (name, category, price, description) VALUES ('Ponds Powder', 'Textiles', 517.97, 'High quality Ponds Powder');
INSERT INTO products (name, category, price, description) VALUES ('Dabur Amla', 'Electronics', 976.59, 'High quality Dabur Amla');
INSERT INTO products (name, category, price, description) VALUES ('Parachute Oil', 'Textiles', 4934.52, 'High quality Parachute Oil');
INSERT INTO products (name, category, price, description) VALUES ('Santoor Soap', 'Pharma', 1346.38, 'High quality Santoor Soap');
INSERT INTO products (name, category, price, description) VALUES ('Patanjali Dant Kanti', 'FMCG', 2392.36, 'High quality Patanjali Dant Kanti');
INSERT INTO products (name, category, price, description) VALUES ('MDH Masala', 'Pharma', 920.31, 'High quality MDH Masala');
INSERT INTO products (name, category, price, description) VALUES ('Everest Masala', 'Electronics', 3591.31, 'High quality Everest Masala');
INSERT INTO products (name, category, price, description) VALUES ('Catch Masala', 'Pharma', 3060.43, 'High quality Catch Masala');
INSERT INTO products (name, category, price, description) VALUES ('Brooke Bond Red Label', 'FMCG', 2987.88, 'High quality Brooke Bond Red Label');
INSERT INTO products (name, category, price, description) VALUES ('Taj Mahal Tea', 'FMCG', 3285.16, 'High quality Taj Mahal Tea');
INSERT INTO products (name, category, price, description) VALUES ('Lipton Green Tea', 'FMCG', 2030.4, 'High quality Lipton Green Tea');
INSERT INTO products (name, category, price, description) VALUES ('Nescafe Classic', 'Groceries', 4459.54, 'High quality Nescafe Classic');
INSERT INTO products (name, category, price, description) VALUES ('Bru Gold', 'Textiles', 898.66, 'High quality Bru Gold');
INSERT INTO products (name, category, price, description) VALUES ('Kissan Jam', 'Electronics', 2991.18, 'High quality Kissan Jam');
INSERT INTO products (name, category, price, description) VALUES ('Kissan Ketchup', 'Pharma', 1360.13, 'High quality Kissan Ketchup');
INSERT INTO products (name, category, price, description) VALUES ('Amul Cheese', 'FMCG', 3630.13, 'High quality Amul Cheese');
INSERT INTO products (name, category, price, description) VALUES ('Mother Dairy Milk', 'Groceries', 811.67, 'High quality Mother Dairy Milk');
INSERT INTO products (name, category, price, description) VALUES ('Nandini Milk', 'Textiles', 3193.75, 'High quality Nandini Milk');
INSERT INTO products (name, category, price, description) VALUES ('Fortune Mustard Oil', 'Groceries', 4621.41, 'High quality Fortune Mustard Oil');
INSERT INTO products (name, category, price, description) VALUES ('Saffola Gold', 'Groceries', 3061.75, 'High quality Saffola Gold');
INSERT INTO products (name, category, price, description) VALUES ('Daawat Basmati', 'Electronics', 2079.89, 'High quality Daawat Basmati');
INSERT INTO products (name, category, price, description) VALUES ('Kohinoor Rice', 'Pharma', 3631.69, 'High quality Kohinoor Rice');
INSERT INTO products (name, category, price, description) VALUES ('India Gate Rice', 'FMCG', 1371.86, 'High quality India Gate Rice');
INSERT INTO products (name, category, price, description) VALUES ('Gokul Milk', 'FMCG', 3274.06, 'High quality Gokul Milk');
INSERT INTO products (name, category, price, description) VALUES ('Vim Liquid', 'Textiles', 3931.14, 'High quality Vim Liquid');
INSERT INTO products (name, category, price, description) VALUES ('Pril Liquid', 'FMCG', 1458.06, 'High quality Pril Liquid');
INSERT INTO products (name, category, price, description) VALUES ('Clinic Plus', 'Electronics', 493.85, 'High quality Clinic Plus');
INSERT INTO products (name, category, price, description) VALUES ('Head & Shoulders', 'Electronics', 1867.45, 'High quality Head & Shoulders');
INSERT INTO products (name, category, price, description) VALUES ('SunSilk', 'Textiles', 3512.1, 'High quality SunSilk');
INSERT INTO products (name, category, price, description) VALUES ('Nirma Powder', 'Groceries', 4057.58, 'High quality Nirma Powder');
INSERT INTO products (name, category, price, description) VALUES ('Tide Powder', 'Textiles', 2890.17, 'High quality Tide Powder');
INSERT INTO products (name, category, price, description) VALUES ('Ariel Powder', 'Textiles', 183.84, 'High quality Ariel Powder');
INSERT INTO products (name, category, price, description) VALUES ('Harpic Toilet Cleaner', 'Electronics', 4781.74, 'High quality Harpic Toilet Cleaner');
INSERT INTO products (name, category, price, description) VALUES ('Lizol Floor Cleaner', 'FMCG', 2659.9, 'High quality Lizol Floor Cleaner');
INSERT INTO products (name, category, price, description) VALUES ('Godrej Aer', 'Textiles', 774.14, 'High quality Godrej Aer');
INSERT INTO products (name, category, price, description) VALUES ('Odonil', 'Pharma', 1597.24, 'High quality Odonil');
INSERT INTO products (name, category, price, description) VALUES ('Cinthol Soap', 'Electronics', 3075.7, 'High quality Cinthol Soap');
INSERT INTO products (name, category, price, description) VALUES ('Margo Soap', 'Electronics', 4118.11, 'High quality Margo Soap');
INSERT INTO products (name, category, price, description) VALUES ('Mysore Sandal', 'FMCG', 2863.52, 'High quality Mysore Sandal');
INSERT INTO products (name, category, price, description) VALUES ('Himalaya Face Wash', 'Textiles', 2274.84, 'High quality Himalaya Face Wash');
INSERT INTO products (name, category, price, description) VALUES ('Garnier Men', 'FMCG', 3768.41, 'High quality Garnier Men');
INSERT INTO products (name, category, price, description) VALUES ('Nivea Cream', 'FMCG', 1728.6, 'High quality Nivea Cream');
INSERT INTO products (name, category, price, description) VALUES ('Vaseline Jelly', 'FMCG', 4456.92, 'High quality Vaseline Jelly');
INSERT INTO products (name, category, price, description) VALUES ('Boroline', 'Electronics', 3668.45, 'High quality Boroline');
INSERT INTO products (name, category, price, description) VALUES ('BoroPlus', 'Pharma', 2675.7, 'High quality BoroPlus');
INSERT INTO products (name, category, price, description) VALUES ('Vicco Turmeric', 'Groceries', 2397.9, 'High quality Vicco Turmeric');
INSERT INTO products (name, category, price, description) VALUES ('Moov', 'Electronics', 897.75, 'High quality Moov');
INSERT INTO products (name, category, price, description) VALUES ('Volini', 'FMCG', 216.25, 'High quality Volini');
INSERT INTO products (name, category, price, description) VALUES ('Iodex', 'FMCG', 1336.56, 'High quality Iodex');
INSERT INTO products (name, category, price, description) VALUES ('Vicks Vaporub', 'Pharma', 2990.06, 'High quality Vicks Vaporub');
INSERT INTO products (name, category, price, description) VALUES ('Amrutanjan', 'Electronics', 4950.85, 'High quality Amrutanjan');
INSERT INTO products (name, category, price, description) VALUES ('Zandu Balm', 'Pharma', 1634.24, 'High quality Zandu Balm');
INSERT INTO products (name, category, price, description) VALUES ('Hajmola', 'Electronics', 871.47, 'High quality Hajmola');
INSERT INTO products (name, category, price, description) VALUES ('Eno Regular', 'Textiles', 1890.58, 'High quality Eno Regular');
INSERT INTO products (name, category, price, description) VALUES ('Kayam Churna', 'Groceries', 2706.95, 'High quality Kayam Churna');
INSERT INTO products (name, category, price, description) VALUES ('Dabur Chyawanprash', 'Textiles', 2837.21, 'High quality Dabur Chyawanprash');
INSERT INTO products (name, category, price, description) VALUES ('Baidyanath Chyawanprash', 'Textiles', 3190.91, 'High quality Baidyanath Chyawanprash');
INSERT INTO products (name, category, price, description) VALUES ('Zandu Kesari Jivan', 'Pharma', 136.79, 'High quality Zandu Kesari Jivan');
INSERT INTO products (name, category, price, description) VALUES ('Horlicks', 'Textiles', 1311.21, 'High quality Horlicks');
INSERT INTO products (name, category, price, description) VALUES ('Bournvita', 'Pharma', 1414.05, 'High quality Bournvita');
INSERT INTO products (name, category, price, description) VALUES ('Complan', 'Electronics', 1613.26, 'High quality Complan');
INSERT INTO products (name, category, price, description) VALUES ('Pediasure', 'Pharma', 2711.15, 'High quality Pediasure');
INSERT INTO products (name, category, price, description) VALUES ('Cerelac', 'Textiles', 1519.24, 'High quality Cerelac');
INSERT INTO products (name, category, price, description) VALUES ('Lactogen', 'FMCG', 2395.02, 'High quality Lactogen');
INSERT INTO products (name, category, price, description) VALUES ('Farex', 'Pharma', 3077.78, 'High quality Farex');
INSERT INTO products (name, category, price, description) VALUES ('Pampers', 'Electronics', 2649.99, 'High quality Pampers');
INSERT INTO products (name, category, price, description) VALUES ('MamyPoko Pants', 'Textiles', 2590.38, 'High quality MamyPoko Pants');
INSERT INTO products (name, category, price, description) VALUES ('Huggies', 'Groceries', 2872.49, 'High quality Huggies');
INSERT INTO products (name, category, price, description) VALUES ('Whisper Choice', 'Pharma', 3125.06, 'High quality Whisper Choice');
INSERT INTO products (name, category, price, description) VALUES ('Stayfree', 'Groceries', 1730.92, 'High quality Stayfree');
INSERT INTO products (name, category, price, description) VALUES ('Sofy', 'Textiles', 1787.2, 'High quality Sofy');
INSERT INTO products (name, category, price, description) VALUES ('Vivel Soap', 'Electronics', 275.29, 'High quality Vivel Soap');
INSERT INTO products (name, category, price, description) VALUES ('Fiama Gel', 'Textiles', 2623.4, 'High quality Fiama Gel');
INSERT INTO products (name, category, price, description) VALUES ('Pears Soap', 'Electronics', 100.23, 'High quality Pears Soap');
INSERT INTO products (name, category, price, description) VALUES ('Dove Soap', 'Pharma', 2573.9, 'High quality Dove Soap');
INSERT INTO products (name, category, price, description) VALUES ('Lux Soap', 'FMCG', 3959.16, 'High quality Lux Soap');
INSERT INTO products (name, category, price, description) VALUES ('Rexona Deo', 'Pharma', 105.13, 'High quality Rexona Deo');
INSERT INTO products (name, category, price, description) VALUES ('Engage Deo', 'Textiles', 3132.21, 'High quality Engage Deo');
INSERT INTO products (name, category, price, description) VALUES ('Fogg Deo', 'Electronics', 2755.39, 'High quality Fogg Deo');
INSERT INTO products (name, category, price, description) VALUES ('Wild Stone', 'FMCG', 477.62, 'High quality Wild Stone');
INSERT INTO products (name, category, price, description) VALUES ('Park Avenue', 'FMCG', 658.67, 'High quality Park Avenue');
INSERT INTO products (name, category, price, description) VALUES ('Axe Deo', 'Electronics', 3699.0, 'High quality Axe Deo');
INSERT INTO products (name, category, price, description) VALUES ('Navratna Oil', 'Pharma', 2409.39, 'High quality Navratna Oil');
INSERT INTO products (name, category, price, description) VALUES ('Himani Navratna', 'Electronics', 2797.25, 'High quality Himani Navratna');
INSERT INTO products (name, category, price, description) VALUES ('Dermicool', 'Groceries', 4695.55, 'High quality Dermicool');
INSERT INTO products (name, category, price, description) VALUES ('Nycil', 'Pharma', 1419.26, 'High quality Nycil');
INSERT INTO products (name, category, price, description) VALUES ('Sony Bravia TV', 'Groceries', 4888.04, 'High quality Sony Bravia TV');
INSERT INTO products (name, category, price, description) VALUES ('Samsung Galaxy', 'Pharma', 1363.09, 'High quality Samsung Galaxy');
INSERT INTO products (name, category, price, description) VALUES ('Poco X3', 'Pharma', 2551.78, 'High quality Poco X3');
INSERT INTO products (name, category, price, description) VALUES ('Redmi Note', 'Textiles', 1216.8, 'High quality Redmi Note');
INSERT INTO products (name, category, price, description) VALUES ('Vivo V20', 'Pharma', 605.63, 'High quality Vivo V20');
INSERT INTO products (name, category, price, description) VALUES ('Oppo F17', 'Textiles', 646.77, 'High quality Oppo F17');
INSERT INTO products (name, category, price, description) VALUES ('OnePlus Nord', 'FMCG', 4010.75, 'High quality OnePlus Nord');
INSERT INTO products (name, category, price, description) VALUES ('Micromax In', 'Groceries', 2083.14, 'High quality Micromax In');
INSERT INTO products (name, category, price, description) VALUES ('Lava Z6', 'Textiles', 810.03, 'High quality Lava Z6');
INSERT INTO products (name, category, price, description) VALUES ('Karbonn', 'Textiles', 4230.86, 'High quality Karbonn');
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (1, 80, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (2, 95, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (3, 462, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (4, 429, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (5, 478, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (6, 147, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (7, 71, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (8, 11, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (9, 212, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (10, 61, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (11, 392, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (12, 18, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (13, 217, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (14, 417, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (15, 202, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (16, 438, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (17, 306, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (18, 96, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (19, 100, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (20, 474, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (21, 490, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (22, 170, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (23, 295, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (24, 446, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (25, 142, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (26, 357, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (27, 382, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (28, 267, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (29, 368, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (30, 137, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (31, 499, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (32, 271, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (33, 42, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (34, 351, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (35, 42, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (36, 452, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (37, 97, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (38, 162, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (39, 424, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (40, 61, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (41, 373, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (42, 251, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (43, 166, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (44, 337, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (45, 54, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (46, 213, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (47, 125, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (48, 149, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (49, 484, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (50, 413, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (51, 387, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (52, 46, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (53, 140, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (54, 349, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (55, 157, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (56, 246, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (57, 392, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (58, 114, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (59, 116, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (60, 293, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (61, 166, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (62, 56, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (63, 456, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (64, 301, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (65, 372, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (66, 137, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (67, 112, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (68, 440, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (69, 157, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (70, 66, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (71, 101, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (72, 363, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (73, 405, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (74, 265, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (75, 380, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (76, 405, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (77, 164, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (78, 244, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (79, 482, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (80, 297, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (81, 334, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (82, 398, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (83, 123, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (84, 208, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (85, 151, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (86, 276, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (87, 149, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (88, 405, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (89, 197, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (90, 285, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (91, 228, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (92, 150, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (93, 403, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (94, 88, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (95, 53, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (96, 347, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (97, 290, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (98, 278, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (99, 380, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (100, 482, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (101, 421, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (102, 455, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (103, 359, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (104, 442, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (105, 186, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (106, 107, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (107, 72, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (108, 252, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (109, 9, 20);
INSERT INTO stock_levels (product_id, quantity, low_stock_threshold) VALUES (110, 456, 20);
